# 线上配置文件
server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.96.6.72:3306/fengoj
    username: root
    password: 285828
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 0
    host: 47.96.6.72
    port: 6380
    timeout: 5000
    password: mnbv123456
  # Elasticsearch 配置
  # todo 需替换配置
  #elasticsearch:
  #  uris: http://localhost:9200
  #  username: root
  #  password: 123456
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''